//! Execution witnesses for every callable signature in the pinned jq manual.
//!
//! The compatibility campaign owns exact values and process contracts.  This
//! matrix is the lower-level completeness guard: every advertised name/arity
//! is parsed, resolved, compiled, and pulled through the public VM seam.  A
//! runtime domain/type error is an observable execution, not a substitute for
//! the section-specific value/error/empty cases.

use tq_core::{ResolveOptions, Value, Vm, VmLimits, analyze, parse, resolve};

const DOCUMENTED_SIGNATURES: &[&str] = &[
    "abs/0",
    "acos/0",
    "acosh/0",
    "add/0",
    "add/1",
    "all/0",
    "all/1",
    "all/2",
    "any/0",
    "any/1",
    "any/2",
    "arrays/0",
    "ascii_downcase/0",
    "ascii_upcase/0",
    "asin/0",
    "asinh/0",
    "atan/0",
    "atan2/2",
    "atanh/0",
    "booleans/0",
    "bsearch/1",
    "builtins/0",
    "capture/1",
    "capture/2",
    "cbrt/0",
    "ceil/0",
    "combinations/0",
    "combinations/1",
    "contains/1",
    "copysign/2",
    "cos/0",
    "cosh/0",
    "debug/0",
    "debug/1",
    "del/1",
    "delpaths/1",
    "drem/2",
    "empty/0",
    "endswith/1",
    "env/0",
    "erf/0",
    "erfc/0",
    "error/0",
    "error/1",
    "exp/0",
    "exp10/0",
    "exp2/0",
    "explode/0",
    "expm1/0",
    "fabs/0",
    "fdim/2",
    "finites/0",
    "first/0",
    "first/1",
    "flatten/0",
    "flatten/1",
    "floor/0",
    "fma/3",
    "fmax/2",
    "fmin/2",
    "fmod/2",
    "frexp/0",
    "from_entries/0",
    "fromdate/0",
    "fromdateiso8601/0",
    "fromjson/0",
    "fromstream/1",
    "gamma/0",
    "getpath/1",
    "gmtime/0",
    "group_by/1",
    "gsub/2",
    "gsub/3",
    "halt_error/0",
    "halt_error/1",
    "halt/0",
    "has/1",
    "have_decnum/0",
    "have_literal_numbers/0",
    "hypot/2",
    "implode/0",
    "in/1",
    "IN/1",
    "IN/2",
    "index/1",
    "INDEX/2",
    "indices/1",
    "infinite/0",
    "input_filename/0",
    "input_line_number/0",
    "input/0",
    "inputs/0",
    "inside/1",
    "isempty/1",
    "isfinite/0",
    "isinfinite/0",
    "isnan/0",
    "isnormal/0",
    "iterables/0",
    "j0/0",
    "j1/0",
    "jn/2",
    "join/1",
    "JOIN/2",
    "JOIN/3",
    "JOIN/4",
    "keys_unsorted/0",
    "keys/0",
    "last/0",
    "last/1",
    "ldexp/2",
    "length/0",
    "lgamma/0",
    "limit/2",
    "localtime/0",
    "log/0",
    "log10/0",
    "log1p/0",
    "log2/0",
    "logb/0",
    "ltrim/0",
    "ltrimstr/1",
    "map_values/1",
    "map/1",
    "match/1",
    "match/2",
    "max_by/1",
    "max/0",
    "min_by/1",
    "min/0",
    "mktime/0",
    "modf/0",
    "modulemeta/0",
    "nan/0",
    "nearbyint/0",
    "nextafter/2",
    "nexttoward/2",
    "normals/0",
    "not/0",
    "now/0",
    "nth/1",
    "nth/2",
    "nulls/0",
    "numbers/0",
    "objects/0",
    "path/1",
    "paths/0",
    "paths/1",
    "pick/1",
    "pow/2",
    "range/1",
    "range/2",
    "range/3",
    "recurse/0",
    "recurse/1",
    "recurse/2",
    "remainder/2",
    "repeat/1",
    "reverse/0",
    "rindex/1",
    "rint/0",
    "round/0",
    "rtrim/0",
    "rtrimstr/1",
    "scalars/0",
    "scalb/2",
    "scalbln/2",
    "scan/1",
    "scan/2",
    "select/1",
    "setpath/2",
    "significand/0",
    "sin/0",
    "sinh/0",
    "skip/2",
    "sort_by/1",
    "sort/0",
    "split/1",
    "split/2",
    "splits/1",
    "splits/2",
    "sqrt/0",
    "startswith/1",
    "stderr/0",
    "strflocaltime/1",
    "strftime/1",
    "strings/0",
    "strptime/1",
    "sub/2",
    "sub/3",
    "tan/0",
    "tanh/0",
    "test/1",
    "test/2",
    "tgamma/0",
    "to_entries/0",
    "toboolean/0",
    "todate/0",
    "todateiso8601/0",
    "tojson/0",
    "tonumber/0",
    "tostream/0",
    "tostring/0",
    "transpose/0",
    "trim/0",
    "trimstr/1",
    "trunc/0",
    "truncate_stream/1",
    "type/0",
    "unique_by/1",
    "unique/0",
    "until/2",
    "utf8bytelength/0",
    "values/0",
    "walk/1",
    "while/2",
    "with_entries/1",
    "y0/0",
    "y1/0",
    "yn/2",
];

#[test]
fn every_documented_signature_reaches_the_public_vm() {
    assert_eq!(DOCUMENTED_SIGNATURES.len(), 220);

    for signature in DOCUMENTED_SIGNATURES {
        let (name, arity) = signature
            .rsplit_once('/')
            .expect("inventory signatures use name/arity");
        let arity: usize = arity.parse().expect("inventory arity is numeric");
        let arguments = match arity {
            0 => String::new(),
            1 => "0".to_owned(),
            2 => "0; 0".to_owned(),
            3 => "0; 0; 0".to_owned(),
            4 => "0; 0; 0; 0".to_owned(),
            _ => panic!("unexpected documented arity {arity} for {name}"),
        };
        let query = if arguments.is_empty() {
            name.to_owned()
        } else {
            format!("{name}({arguments})")
        };
        let plan = analyze(
            resolve(
                parse(&query).expect("documented signature parses"),
                &ResolveOptions::default(),
            )
            .expect("documented signature resolves"),
        )
        .compile()
        .expect("documented signature compiles")
        .document_plan();
        let mut vm = Vm::new(
            &plan,
            Value::Null,
            VmLimits {
                steps: 64,
                ..VmLimits::default()
            },
        );
        // Type/domain errors, empty output, and bounded resource errors are
        // all valid witnesses here; the section ledgers assert their exact
        // jq contracts.  Pulling once proves the call is executable.
        let _ = vm.next_result();
    }
}
